* src/etc/munge.init: Added Should-Start & Should-Stop LSB headers.   Changed return code for invalid or excess args to match LSB spec.   Changed return code for unimplemented feature to match LSB spec.   Tweaked comments & syntax.  Tweaked SuSE try-restart behavior.

diff --git a/src/etc/munge.init b/src/etc/munge.init
--- a/src/etc/munge.init
+++ b/src/etc/munge.init
@@ -8,7 +8,9 @@
 # Provides:       munge
 # Required-Start: $named $time
 # Required-Stop:  $named $time
-# Default-Start:  3 5
+# Should-Start:   $local_fs $syslog
+# Should-Stop:    $local_fs $syslog
+# Default-Start:  3 4 5
 # Default-Stop:   0 1 2 6
 # Description:    Start the MUNGE user authentication service.
 ### END INIT INFO
@@ -19,7 +21,7 @@ DAEMON="/usr/sbin/munged"
 
 PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
 
-[ -x "${DAEMON}" ] || exit 5
+[ -x "$DAEMON" ] || exit 5              # error: program is not installed
 
 [ -f /etc/sysconfig/munge ] && source /etc/sysconfig/munge
 
@@ -27,19 +29,20 @@ PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin
 
 service_init ()
 {
-#  Determine the system type and initialize the environment.
+# Determine the system type and initialize the environment.
 #
-#  Note that the shell positional parameters must be preserved when calling
-#    this function in order for SuSE to initialize its environment properly.
-#
+# Note that the shell positional parameters must be preserved when calling
+#   this function in order for SuSE to initialize its environment properly.
+##
   local RH_SUBSYS_BASENAME
 
+  rc=0
   if test -f /etc/init.d/functions; then
     SYSTEM="REDHAT"
     source /etc/init.d/functions
     RH_SUBSYS_BASENAME="`echo $0 | perl -pe 's,(.*/)?([SK][0-9]{2})?(.*),$3,'`"
-    RH_SUBSYS="/var/lock/subsys/${RH_SUBSYS_BASENAME}"
-    INITLOG_ARGS=""                     # Disable RH suppression of stderr msgs
+    RH_SUBSYS="/var/lock/subsys/$RH_SUBSYS_BASENAME"
+    INITLOG_ARGS=""                     # disable RH suppression of stderr msgs
   elif test -f /etc/rc.status; then
     SYSTEM="SUSE"
     source /etc/rc.status
@@ -56,9 +59,9 @@ service_init ()
 
 service_fini ()
 {
-#  Return the exit status.
-#
-  case ${SYSTEM} in
+# Return the exit status.
+##
+  case "$SYSTEM" in
     SUSE)
       rc_exit
       ;;
@@ -72,31 +75,34 @@ service_fini ()
 
 service_start ()
 {
-# Start the service.  Required by LSB.
+# Start the service.
+# Required by LSB.
 #
-  echo -n "Starting ${SERVICE}: "
-  case ${SYSTEM} in
+# Running "start" on a service already running should be considered successful.
+##
+  echo -n "Starting $SERVICE: "
+  case "$SYSTEM" in
     LSB)
-      start_daemon ${DAEMON} ${OPTIONS} --force
+      start_daemon "$DAEMON" $OPTIONS --force
       rc=$?
       [ $rc -eq 0 ] && log_success_msg || log_failure_msg
       ;;
     REDHAT)
-      status ${DAEMON} >/dev/null
+      status "$DAEMON" >/dev/null
       rc=$?
       if [ $rc -ne 0 ]; then
-        daemon ${DAEMON} ${OPTIONS} --force
+        daemon "$DAEMON" $OPTIONS --force
         rc=$?
       fi
       echo
-      [ $rc -eq 0 ] && touch ${RH_SUBSYS} 2>/dev/null
+      [ $rc -eq 0 ] && touch "$RH_SUBSYS" 2>/dev/null
       ;;
     SUSE)
-      startproc ${DAEMON} ${OPTIONS} --force
+      startproc "$DAEMON" $OPTIONS --force
       rc_status -v
       ;;
     *)
-      ${DAEMON} ${OPTIONS} --force 2>/dev/null
+      "$DAEMON" $OPTIONS --force 2>/dev/null
       rc=$?
       [ $rc -eq 0 ] && echo success || echo failure
       ;;
@@ -107,27 +113,31 @@ service_start ()
 
 service_stop ()
 {
-# Stop the service.  Required by LSB.
+# Stop the service.
+# Required by LSB.
 #
-  echo -n "Stopping ${SERVICE}: "
-  case ${SYSTEM} in
+# Running "stop" on a service already stopped or not running should be
+#   considered successful.
+##
+  echo -n "Stopping $SERVICE: "
+  case "$SYSTEM" in
     LSB)
-      killproc ${DAEMON}
+      killproc "$DAEMON"
       rc=$?
       [ $rc -eq 0 ] && log_success_msg || log_failure_msg
       ;;
     REDHAT)
-      killproc ${DAEMON}
+      killproc "$DAEMON"
       rc=$?
       echo
-      [ $rc -eq 0 ] && rm -f ${RH_SUBSYS} 2>/dev/null
+      [ $rc -eq 0 ] && rm -f "$RH_SUBSYS" 2>/dev/null
       ;;
     SUSE)
-      killproc ${DAEMON}
+      killproc "$DAEMON"
       rc_status -v
       ;;
     *)
-      rc=4 # FIXME
+      rc=3                              # FIXME: error: unimplemented feature
       [ $rc -eq 0 ] && echo success || echo failure
       ;;
   esac
@@ -137,13 +147,17 @@ service_stop ()
 
 service_restart ()
 {
-# Stop and restart the service if the service is already running,
-#   otherwise start the service.  Required by LSB.
+# Stop and restart the service if it is already running;
+#   otherwise, start the service.
+# Required by LSB.
 #
+# Running "restart" on a service already stopped or not running should be
+#   considered successful.
+##
   $0 stop
   $0 start
 
-  case ${SYSTEM} in
+  case "$SYSTEM" in
     SUSE)
       rc_status
       ;;
@@ -157,16 +171,19 @@ service_restart ()
 
 service_try_restart ()
 {
-# Restart the service if the service is already running.  Optional for LSB.
+# Restart the service if it is already running.
+# Optional for LSB.  Also known as "condrestart" by RedHat.
 #
-  rc=0
-  case ${SYSTEM} in
+# Running "try-restart" on a service already stopped or not running should be
+#   considered successful.
+##
+  case "$SYSTEM" in
     REDHAT)
-      [ -f ${RH_SUBSYS} ] && $0 restart || :
+      [ -f "$RH_SUBSYS" ] && $0 restart || :
       rc=$?
       ;;
     SUSE)
-      $0 status >/dev/null && $0 restart || :
+      $0 status >/dev/null && $0 restart || rc_reset
       rc_status
       ;;
     LSB|*)
@@ -180,12 +197,12 @@ service_try_restart ()
 
 service_reload ()
 {
-# Cause the configuration of the service to be reloaded without actually
-#   stopping and restarting the service.  Optional for LSB.
-#
-  rc=4 # FIXME
-  echo -n "Reloading ${SERVICE}: "
-  case ${SYSTEM} in
+# Reload the configuration without stopping and restarting the service.
+# Optional for LSB.
+##
+  rc=3                                  # error: unimplemented feature
+  echo -n "Reloading $SERVICE: "
+  case "$SYSTEM" in
     LSB)
       [ $rc -eq 0 ] && log_success_msg || log_failure_msg
       ;;
@@ -207,12 +224,16 @@ service_reload ()
 
 service_force_reload ()
 {
-# Cause the configuration of the service to be reloaded if the service supports
-#   this, otherwise restart the service if it is running.  Required by LSB.
-#
+# Reload the configuration if the service supports this;
+#   otherwise, restart the service if it is already running.
+# Required by LSB.
+# 
+# Running "force-reload" on a service already stopped or not running should be
+#   considered successful.
+##
   $0 try-restart
 
-  case ${SYSTEM} in
+  case "$SYSTEM" in
     SUSE)
       rc_status
       ;;
@@ -226,29 +247,30 @@ service_force_reload ()
 
 service_status ()
 {
-# Print the current status of the service.  Required by LSB.
-#
-  case ${SYSTEM} in
+# Print the current status of the service.
+# Required by LSB.
+##
+  case "$SYSTEM" in
     LSB)
-      pids=`pidofproc ${DAEMON} 2>/dev/null`
+      pids=`pidofproc "$DAEMON" 2>/dev/null`
       rc=$?
       if [ $rc -eq 0 ]; then
-        echo "${DAEMON} (pid $pids) is running..."
+        echo "`basename $DAEMON` (pid $pids) is running..."
       else
-        echo "${DAEMON} is stopped"
+        echo "`basename $DAEMON` is stopped"
       fi
       ;;
     REDHAT)
-      status ${DAEMON}
+      status "$DAEMON"
       rc=$?
       ;;
     SUSE)
-      echo -n "Checking for ${SERVICE}: "
-      checkproc ${DAEMON}
+      echo -n "Checking for $SERVICE: "
+      checkproc "$DAEMON"
       rc_status -v
       ;;
     *)
-      rc=4 # FIXME
+      rc=3                              # FIXME: error: unimplemented feature
       [ $rc -eq 0 ] && echo success || echo failure
       ;;
   esac
@@ -256,7 +278,6 @@ service_status ()
 
 ###############################################################################
 
-rc=4
 service_init "$@"
 
 case "$1" in
@@ -283,8 +304,8 @@ case "$1" in
     ;;
   *)
     COMMANDS="start|stop|restart|try-restart|reload|force-reload|status"
-    echo "Usage: $0 {${COMMANDS}}"
-    exit 1
+    echo "Usage: `basename $0` ($COMMANDS)"
+    exit 2                              # error: invalid or excess argument(s)
     ;;
 esac
 
