Added support for the "--enable-debug" configure script option.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1018,6 +1018,7 @@ Optional Features:
   --enable-static=PKGS  build static libraries default=yes
   --enable-fast-install=PKGS  optimize for fast installation default=yes
   --disable-libtool-lock  avoid locking (might break parallel builds)
+  --enable-debug          enable debugging code for development
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1975,13 +1976,6 @@ fi
   MAINT=$MAINTAINER_MODE_TRUE
 
 
-
-##
-# Read META information.
-##
-#NAME="`perl -ne 'print,exit if s/^\s*NAME:\s*(\S*).*/\1/i' $srcdir/META`"
-#AC_DEFINE_UNQUOTED([NAME], ["$NAME"], [Define the project's name.])
-#AC_SUBST([NAME])
 
 ##
 # Checks for programs.
@@ -4646,7 +4640,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4649 "configure"' > conftest.$ac_ext
+  echo '#line 4643 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5175,7 +5169,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5178: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5172: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6359,7 +6353,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6362 "configure"' > conftest.$ac_ext
+    echo '#line 6356 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7031,7 +7025,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7034 "configure"
+#line 7028 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7129,7 +7123,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7132 "configure"
+#line 7126 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7886,6 +7880,42 @@ echo "${ECHO_T}no" >&6
 fi
 
 
+  echo "$as_me:$LINENO: checking whether debugging is enabled" >&5
+echo $ECHO_N "checking whether debugging is enabled... $ECHO_C" >&6
+  # Check whether --enable-debug or --disable-debug was given.
+if test "${enable_debug+set}" = set; then
+  enableval="$enable_debug"
+   case "$enableval" in
+        yes) ac_debug=yes ;;
+        no)  ac_debug=no ;;
+        *)   echo "$as_me:$LINENO: result: doh!" >&5
+echo "${ECHO_T}doh!" >&6
+             { { echo "$as_me:$LINENO: error: bad value \"$enableval\" for --enable-debug" >&5
+echo "$as_me: error: bad value \"$enableval\" for --enable-debug" >&2;}
+   { (exit 1); exit 1; }; } ;;
+      esac
+
+
+fi;
+  if test "$ac_debug" = yes; then
+    if test -z "$ac_save_CFLAGS"; then
+      test "$ac_cv_prog_cc_g" = yes && CFLAGS="-g"
+      test "$GCC" = yes && CFLAGS="$CFLAGS -Wall -Werror"
+    fi
+  else
+    if test -z "$ac_save_CFLAGS"; then
+      test "$GCC" = yes && CFLAGS="-O2 -Wall" || CFLAGS="-O"
+    fi
+
+cat >>confdefs.h <<\_ACEOF
+#define NDEBUG 1
+_ACEOF
+
+  fi
+  echo "$as_me:$LINENO: result: ${ac_debug=no}" >&5
+echo "${ECHO_T}${ac_debug=no}" >&6
+
+
 ##
 # Checks for libraries.
 ##
@@ -8602,6 +8632,7 @@ fi
 
 ##
 # Checks for OpenSSL library functions.
+#   Prevent libcrypto from being linked into all binaries.
 ##
 ac_save_LIBS="$LIBS"
 
@@ -8765,7 +8796,8 @@ done
 LIBS="$ac_save_LIBS"
 
 ##
-# Checks for Pthreads
+# Checks for Pthreads.
+#   Prevent libpthread from being linked into all binaries.
 ##
 ac_save_LIBS="$LIBS"
 
@@ -8837,7 +8869,6 @@ LIBS="$ac_save_LIBS"
 ##
 # Checks for library functions.
 ##
-#AC_FUNC_MALLOC
 
 
 for ac_func in \
