* README.AIX, munge.spec, config/x_ac_arch.m4: Fixed so 32-bit &   64-bit builds work on AIX without a gcc wrapper script setting either   "-maix32" or "-maix64".

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3443,6 +3443,7 @@ fi
 
 
 
+
   echo "$as_me:$LINENO: checking for specified code architecture" >&5
 echo $ECHO_N "checking for specified code architecture... $ECHO_C" >&6
   # Check whether --enable-arch or --disable-arch was given.
@@ -3463,11 +3464,12 @@ fi;
   echo "$as_me:$LINENO: result: ${x_ac_arch=no}" >&5
 echo "${ECHO_T}${x_ac_arch=no}" >&6
 
-  echo "$as_me:$LINENO: checking whether $CC accepts -m${x_ac_arch}" >&5
+  if test "$x_ac_arch" != "no"; then
+    echo "$as_me:$LINENO: checking whether $CC accepts -m${x_ac_arch}" >&5
 echo $ECHO_N "checking whether $CC accepts -m${x_ac_arch}... $ECHO_C" >&6
-  _x_ac_arch_cflags_save="$CFLAGS"
-  CFLAGS="$CFLAGS -m${x_ac_arch}"
-  cat >conftest.$ac_ext <<_ACEOF
+    _x_ac_arch_cflags_save="$CFLAGS"
+    CFLAGS="$CFLAGS -m${x_ac_arch}"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -3511,8 +3513,62 @@ sed 's/^/| /' conftest.$ac_ext >&5
 x_ac_arch_prog_cc_m=no; CFLAGS="$_x_ac_arch_cflags_save"
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-  echo "$as_me:$LINENO: result: ${x_ac_arch_prog_cc_m=no}" >&5
+    echo "$as_me:$LINENO: result: ${x_ac_arch_prog_cc_m=no}" >&5
 echo "${ECHO_T}${x_ac_arch_prog_cc_m=no}" >&6
+
+    if expr "$host_os" : "aix" >/dev/null 2>&1; then
+      echo "$as_me:$LINENO: checking whether $CC accepts -maix${x_ac_arch}" >&5
+echo $ECHO_N "checking whether $CC accepts -maix${x_ac_arch}... $ECHO_C" >&6
+      _x_ac_arch_cflags_save="$CFLAGS"
+      CFLAGS="$CFLAGS -maix${x_ac_arch}"
+      cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  x_ac_arch_prog_cc_maix=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+x_ac_arch_prog_cc_maix=no; CFLAGS="$_x_ac_arch_cflags_save"
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+      echo "$as_me:$LINENO: result: ${x_ac_arch_prog_cc_maix=no}" >&5
+echo "${ECHO_T}${x_ac_arch_prog_cc_maix=no}" >&6
+    fi
+  fi
 
   if test "$x_ac_arch" == "32"; then
     if expr "$host_os" : "aix" >/dev/null 2>&1; then
@@ -3538,6 +3594,10 @@ echo "$as_me: error: The OBJECT_MODE variable must be exported to the shell." >&
         && LDFLAGS="-L/lib64 -L/usr/lib64 $LDFLAGS"
     fi
     unset x_ac_cv_check_ssl_dir
+  else
+    if expr "$host_os" : "aix" >/dev/null 2>&1; then
+      OBJECT_MODE="$_x_ac_arch_objmode_save"
+    fi
   fi
 
 
@@ -6710,7 +6770,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 6713 "configure"
+#line 6773 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6808,7 +6868,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 6811 "configure"
+#line 6871 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6957,7 +7017,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6960 "configure"' > conftest.$ac_ext
+  echo '#line 7020 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7645,11 +7705,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7708: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7652: \$? = $ac_status" >&5
+   echo "$as_me:7712: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7939,11 +7999,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7942: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8002: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7946: \$? = $ac_status" >&5
+   echo "$as_me:8006: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8043,11 +8103,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8046: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8106: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8050: \$? = $ac_status" >&5
+   echo "$as_me:8110: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8099,11 +8159,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8102: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8162: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8106: \$? = $ac_status" >&5
+   echo "$as_me:8166: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
