Added Make-rpm.mk include.

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -115,7 +115,7 @@ all: all-recursive
 
 am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
  configure.lineno
-$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
+$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ Makefile.am $(srcdir)/config/Make-rpm.mk $(top_srcdir)/configure.ac $(ACLOCAL_M4)
 	cd $(top_srcdir) && \
 	  $(AUTOMAKE) --gnu  Makefile
 Makefile: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.in  $(top_builddir)/config.status
@@ -450,6 +450,77 @@ uninstall-info: uninstall-info-recursive
 	uninstall uninstall-am uninstall-info-am \
 	uninstall-info-recursive uninstall-recursive
 
+
+tar rpm:
+	@proj=$(PACKAGE); if test -z "$$proj"; then \
+	  echo "ERROR: PACKAGE macro def is not defined." 1>&2; exit 1; fi; \
+	if test -z "$$tag"; then \
+	  if ! test -f META; then \
+	    echo "ERROR: Cannot find $$proj metadata in \"`pwd`/META\"." 1>&2;\
+	      exit 1; fi; \
+	  name=`perl -ne 'print,exit if s/^\s*NAME:\s*(\S*).*/\1/i' META`; \
+	  ver=`perl -ne 'print,exit if s/^\s*VERSION:\s*(\S*).*/\1/i' META`; \
+	  rel=`perl -ne 'print,exit if s/^\s*RELEASE:\s*(\S*).*/\1/i' META`; \
+	  test -z "$$rel" && pkg=$$name-$$ver || pkg=$$name-$$ver-$$rel; \
+	  tag=`echo $$pkg | sed 's/\./-/g'`; fi; \
+	tmp=$${TMPDIR-/tmp}/tmp-$$proj-$$$$; \
+	rm -rf $$tmp || exit 1; \
+	test -n "$(mkinstalldirs)" \
+	  && mkdir="$(mkinstalldirs)" || mkdir="mkdir -p"; \
+	if ! $$mkdir $$tmp >/dev/null; then \
+	  echo "ERROR: Cannot create \"$$tmp\" dir." 1>&2; exit 1; fi; \
+	test -f CVS/Root && cvs="cvs -d `cat CVS/Root`" || cvs="cvs"; \
+	echo "Fetching $$proj from CVS (tag=$$tag) ..."; \
+	(cd $$tmp; $$cvs -Q export -kv -r $$tag $$proj) || exit 1; \
+	meta=$$tmp/$$proj/META; \
+	if test ! -f "$$meta"; then \
+	  echo "ERROR: Cannot find $$proj metadata in CVS." 1>&2; exit 1; fi; \
+	name=`perl -ne 'print,exit if s/^\s*NAME:\s*(\S*).*/\1/i' $$meta`; \
+	if test "$$proj" != "$$name"; then \
+	  echo "ERROR: PACKAGE does not match metadata." 1>&2; exit 1; fi; \
+	ver=`perl -ne 'print,exit if s/^\s*VERSION:\s*(\S*).*/\1/i' $$meta`; \
+	rel=`perl -ne 'print,exit if s/^\s*RELEASE:\s*(\S*).*/\1/i' $$meta`; \
+	test "$$tag" = "HEAD" && rel="`date +%y%m%d%H%M`"; \
+	if test -n "$$rel"; then pkg=$$proj-$$ver-$$rel; \
+	  else pkg=$$proj-$$ver; test -n "$$rev" -a "$$tag" = "HEAD" \
+	    && rel="$$rev" || rel="1"; fi; \
+	mv "$$tmp/$$proj" "$$tmp/$$proj-$$ver" || exit 1; \
+	$(MAKE) -s $@-internal mkdir="$$mkdir" tmp="$$tmp" \
+	  proj="$$proj" pkg="$$pkg" ver="$$ver" rel="$$rel" \
+	    && rm -rf $$tmp
+
+tar-internal:
+	@echo "Creating $$pkg.tgz ..."; \
+	rm -f $$pkg.tgz || exit 1; \
+	(cd $$tmp; tar -cf - $$proj-$$ver) | gzip -c9 >$$tmp/$$pkg.tgz; \
+	cp -p $$tmp/$$pkg.tgz $$pkg.tgz || exit 1
+
+rpm-internal: tar-internal
+	@echo "Creating $$pkg*rpm ..."; \
+	for d in BUILD RPMS SOURCES SPECS SRPMS TMP; do \
+	  if ! $$mkdir $$tmp/$$d >/dev/null; then \
+	    echo "ERROR: Cannot create \"$$tmp/$$d\" dir." 1>&2; exit 1; fi; \
+	      done; \
+	mv $$tmp/$$pkg.tgz $$tmp/SOURCES/ || exit 1; \
+	test -f $$tmp/$$proj-$$ver/$$proj.spec.in \
+	  && spec=$$tmp/$$proj-$$ver/$$proj.spec.in \
+	  || spec=$$tmp/$$proj-$$ver/$$proj.spec; \
+	if ! test -f $$spec; then \
+	  echo "ERROR: Cannot find $$proj spec file in CVS." 1>&2; exit 1; fi;\
+	sed -e "s/^\([ 	]*Name:\).*/\1 $$proj/i" \
+	    -e "s/^\([ 	]*Version:\).*/\1 $$ver/i" \
+	    -e "s/^\([ 	]*Release:\).*/\1 $$rel/i" \
+	    -e "s/^\([ 	]*Source0\?:\).*/\1 $$pkg.tgz/i" \
+	    <$$spec >$$tmp/SPECS/$$proj.spec; \
+	if ! test -s $$tmp/SPECS/$$proj.spec; then \
+	  echo "ERROR: Cannot create $$proj.spec." 1>&2; exit 1; fi; \
+	rpm --showrc | egrep "[[:space:]]_(gpg|pgp)_name[[:space:]]" \
+	  >/dev/null && sign="--sign"; \
+	if ! rpm -ba --define "_tmppath $$tmp/TMP" --define "_topdir $$tmp" \
+	  $$sign --quiet $$tmp/SPECS/$$proj.spec >$$tmp/rpm.log 2>&1; then \
+	    cat $$tmp/rpm.log; exit 1; fi; \
+	cp -p $$tmp/RPMS/*/$$proj-*.rpm $$tmp/SRPMS/$$proj-*.src.rpm . \
+	  || exit 1
 
 distclean-local:
 	-rm -fr autom4te*.cache autoscan.*
